// data-bombard.js — Quatryl Bombard (Target class)
// Guide sources: BGG reviews, designer interview, community first-look, playtester notes
// Card images: github.com/any2cards/worldhaven character-ability-cards/crimson-scales/bm/cs-{slug}.png
// Class code: BM

const BASE_BM = "https://raw.githubusercontent.com/any2cards/worldhaven/master/images/character-ability-cards/crimson-scales/bm/";
const BASE_WH_BM = "https://raw.githubusercontent.com/any2cards/worldhaven/master/images/";

const BOMBARD_DATA = {
  id: "bombard",
  name: "Quatryl Bombard",
  symbol: "Target",
  game: "Crimson Scales",
  startingHP: 10,
  handSize: 9,

  milestone: {
    imageUrl: BASE_WH_BM + "milestones/crimson-scales/cs-ms-bombard-front.png",
    reward: "Permanently add <strong>Pummeling Chain</strong> (Level M card) to your hand. At Initiative 17 it slots neatly into the Bombard's late/early initiative strategy, and adds another Projectile trigger opportunity toward future milestone progress.",
    commentary: "Goal: Trigger a Projectile ability ten (10) times. This rewards leaning into the class's signature mechanic rather than avoiding it. Since Projectile placement is how the Bombard sets up its most powerful attacks, active players will accumulate milestone checks naturally through normal play. The 9-card hand means every card matters — tracking Projectile triggers is a natural byproduct of good play.",
  },

  cards: [
    // ── LEVEL 1 ────────────────────────────────────────────
    {
      name: "Barbed Armor",
      level: "1",
      initiative: 13,
      imageUrl: BASE_BM + "cs-barbed-armor.png",
      tags: ["shield", "retaliate"],
      builds: ["tank"],
      top: { text: "Shield and Retaliate effect", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "The top is a fast initiative Retaliate 1 that also applies Wound to any enemy suffering damage from the Retaliate. Play this with the persistent bottom of Ignited Launch for a round of Retaliate 3 with Wound — absolutely filthy. The bottom is the alternative tank play, gaining Shield 2 against melee attacks. Coupled with the top of Rolling into Position and you have a potential Shield 3 for the round.",
    },
    {
      name: "Consistent Firing",
      level: "1",
      initiative: 76,
      imageUrl: BASE_BM + "cs-consistent-firing.png",
      tags: ["projectile", "attack"],
      builds: ["projectile"],
      top: { text: "Projectile placement or ranged attack", isLoss: false },
      bottom: { text: "Move or reposition", isLoss: false },
      commentary: "The first Projectile ability fires a projectile at Range 3 and then next round does three separate attacks of Attack 1, Attack 1 PIERCE 1, and Attack 1 PIERCE 2 to the enemy occupying the target hex. The piercing will keep this Level 1 card relevant at higher levels. The bottom is a standard Move 2 with an added buff of advantage on your next attack. Both top and bottom gain XP as an added bonus. Seems like a staple card at least for the first few levels.",
    },
    {
      name: "Double Cannons",
      level: "1",
      initiative: 60,
      imageUrl: BASE_BM + "cs-double-cannons.png",
      tags: ["attack", "aoe", "shield", "ranged"],
      builds: ["projectile"],
      top: { text: "AoE attack, double cannon fire", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "Great value at Attack 3 on a 2-hex ranged AoE. The downside is Range 2, but at least the range can be enhanced. Not a Projectile attack, so the damage is applied immediately. The other downside is the initiative 60 for the bottom Shield 2 against ranged attacks, which requires pairing with a quick top. Not a great tank card because it doesn't help against melee attacks.",
    },
    {
      name: "Exploding Cannonball",
      level: "1",
      initiative: 88,
      imageUrl: BASE_BM + "cs-exploding-cannonball.png",
      tags: ["attack", "aoe", "projectile"],
      builds: ["projectile"],
      top: { text: "AoE Loss attack, large explosion", isLoss: true },
      bottom: { text: "Move or reposition", isLoss: false },
      commentary: "This is the BIG ONE — the Bombard's version of a nuke. Huge Projectile Attack 3 PIERCE 1 for a 7-hex AoE at Range 4 that also generates Earth element when fired. Keep in mind: when the Projectile detonates at the start of your turn next round, it detonates on the enemy occupying the target hex, and THAT is the center of the AoE. However, if there is no enemy in the target hex at detonation, none of the attack happens even if enemies are in the other six AoE hexes. This is the critical rule for all Projectile attacks — they can be devastating, but can fizzle completely if the battle map changes before detonation. The 88 initiative lets you go late after enemies move, then act super early the following round to detonate before enemies move again. A classic final room closer — burn cards dramatically impact the 9-card Bombard. The bottom is a Move 3 unaffected by both difficult and hazardous terrain.",
    },
    {
      name: "Forceful Bolt",
      level: "1",
      initiative: 63,
      imageUrl: BASE_BM + "cs-forceful-bolt.png",
      tags: ["attack", "utility"],
      builds: ["both"],
      top: { text: "Ranged attack with Push or control effect", isLoss: false },
      bottom: { text: "Move", isLoss: false },
      commentary: "Decent non-Projectile ranged attack with an additional PUSH 2 effect. The bottom is the commonly frustrating backwards Loot 1 then Move 1 — much prefer to move then loot. Very average card that likely drops from the hand in early level ups.",
    },
    {
      name: "Grappling Hook",
      level: "1",
      initiative: 68,
      imageUrl: BASE_BM + "cs-grappling-hook.png",
      tags: ["move", "utility"],
      builds: ["both"],
      top: { text: "Move with Pull or repositioning utility", isLoss: false },
      bottom: { text: "Attack or utility", isLoss: false },
      commentary: "An interesting take on the PULL mechanic by pulling yourself toward the enemy instead of the other way around — a sneaky form of free movement. Note that the ranged attack happens first and separately from the PULL toward the enemy, so if the attack kills the enemy the pull toward the targeted enemy cannot happen. The bottom is a perfectly serviceable Jump 3.",
    },
    {
      name: "Ignited Launch",
      level: "1",
      initiative: 81,
      imageUrl: BASE_BM + "cs-ignited-launch.png",
      tags: ["projectile", "attack"],
      builds: ["both"],
      top: { text: "Ranged attack or Projectile placement", isLoss: false },
      bottom: { text: "Large Move Loss — repositioning", isLoss: true },
      commentary: "Yes, that is indeed a non-loss Range 4 Attack 5 at Level 1 that also generates Flame. It's a Projectile attack so detonation on the enemy occupying the targeted hex next round is the limitation, as with all of the Bombard's Projectile attacks. The bottom is an interesting 'Stand Your Ground' persistent loss Retaliate 2 tanking ability when you move 1 or fewer hexes on your turn. Maybe a defensive option for the final room, but only works if you can act early every round you're standing your ground.",
    },
    {
      name: "Rolling into Position",
      level: "1",
      initiative: 14,
      imageUrl: BASE_BM + "cs-rolling-into-position.png",
      tags: ["move", "shield"],
      builds: ["both"],
      top: { text: "Fast Move to reposition", isLoss: false },
      bottom: { text: "Utility or minor attack", isLoss: false },
      commentary: "Mediocre tanking top action — just Move 1 and Shield 1 at fast initiative 14. Awkward that it's on the top, but pair it with something like the bottom of Double Cannons for a possible Shield 3. The bottom is a big Move 4 that immobilizes self.",
    },
    {
      name: "Unexpected Bombshell",
      level: "1",
      initiative: 85,
      imageUrl: BASE_BM + "cs-unexpected-bombshell.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Ranged attack with surprise or control effect", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "A non-loss STUN attack at Level 1 in the form of a delayed Projectile attack — though that doesn't help with the traditional use of STUN to neutralize an enemy during the current turn. Targets a detonation hex at Range 4 and also damages all enemies adjacent to the detonation target. The bottom is another grappling hook, and if paired with the top of Grappling Hook you can get up to 7 movement of PULLs toward two separately targeted enemies. Feels like a James Bond combo.",
    },

    // ── LEVEL X ────────────────────────────────────────────
    {
      name: "Chain Grapnel",
      level: "X",
      initiative: 46,
      imageUrl: BASE_BM + "cs-chain-grapnel.png",
      tags: ["utility", "aoe"],
      builds: ["both"],
      top: { text: "Pull or control utility, ranged", isLoss: false },
      bottom: { text: "AoE Pull Loss — group repositioning", isLoss: true },
      commentary: "The first X card has the classic top action of a ranged attack that pulls an enemy and immobilizes it adjacent to you — great for stapling enemies with ranged attacks. The bottom is a non-loss non-damage Projectile 3-hex immobilization AoE for pinning down up to three enemies. A great setup for Exploding Cannonball so enemies won't move before detonation. A card that shines in certain scenarios or with certain party compositions.",
    },
    {
      name: "Man the Cannon",
      level: "X",
      initiative: 21,
      imageUrl: BASE_BM + "cs-man-the-cannon.png",
      tags: ["utility", "support"],
      builds: ["projectile"],
      top: { text: "Powerful Projectile placement or attack Loss", isLoss: true },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "An interesting top persistent loss that grants an adjacent ally an Attack 3 Range 3 at the start of your next four turns — maybe played while standing your ground and tanking to let your ally fire ranged attacks from behind cover. The bottom requires an adjacent ally to forego their top action to give you an Attack 4 Range 3. Is this a 'Hold My Beer' card? The jury is out on how reliably these effects can be coordinated in practice.",
    },
    {
      name: "Pillars of Smoke",
      level: "X",
      initiative: 11,
      imageUrl: BASE_BM + "cs-pillars-of-smoke.png",
      tags: ["utility"],
      builds: ["tank"],
      top: { text: "Create smoke/obstacle hexes, Loss — disrupt enemy pathing", isLoss: true },
      bottom: { text: "Move", isLoss: false },
      commentary: "The top is a persistent loss that grants adjacent allies invisibility when they enter an adjacent hex to you — at the expense of immobilization. An optional effect: allies aren't required to take the invisibility or immobilize. Maybe enables allies to safely long rest. The bottom is the only heal at Level 1, and it's not a particularly strong one. The fact that it grants Disadvantage to all attacks this round is a head-scratcher — it expects you to heal and then absorb attacks in the same round.",
    },

    // ── LEVEL 2 ────────────────────────────────────────────
    {
      name: "Distant Retribution",
      level: "2",
      initiative: 12,
      imageUrl: BASE_BM + "cs-distant-retribution.png",
      tags: ["retaliate", "ranged"],
      builds: ["tank"],
      top: { text: "Ranged Retaliate setup", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "Ranged Retaliate is a situational all-star for the Bombard — unlike most Retaliate options, this one works at range, letting you punish enemies that attack you without needing to be in melee. Very fast initiative 12 gets Retaliate up before enemies act.",
    },
    {
      name: "Rapid Fire",
      level: "2",
      initiative: 41,
      imageUrl: BASE_BM + "cs-rapid-fire.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Multiple Projectile attacks or fast attack Loss", isLoss: true },
      bottom: { text: "Move", isLoss: false },
      commentary: "Aptly named — a burst of ranged fire at medium initiative. The Loss top is a significant commitment on a 9-card class, but multiple hits make it worthwhile for high-HP targets or bosses where the sustained damage matters.",
    },

    // ── LEVEL 3 ────────────────────────────────────────────
    {
      name: "Stationary Enhancements",
      level: "3",
      initiative: 3,
      imageUrl: BASE_BM + "cs-stationary-enhancements.png",
      tags: ["utility", "persistent"],
      builds: ["tank"],
      top: { text: "Persistent buff while not moving", isLoss: false },
      bottom: { text: "Move or setup", isLoss: false },
      commentary: "Initiative 3 — the fastest card in the entire deck, and thematically perfect for a class that often wants to stay still and hold position. The persistent bonus for not moving reinforces the Tank build's stationary firing-line playstyle.",
    },
    {
      name: "Twin Blast",
      level: "3",
      initiative: 80,
      imageUrl: BASE_BM + "cs-twin-blast.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Two Projectile placements or double attack", isLoss: false },
      bottom: { text: "Move", isLoss: false },
      commentary: "Slow initiative 80 is ideal for Projectile setup. Two blasts in one card is excellent value — more Projectile triggers per hand cycle means faster milestone progress and more damage throughput.",
    },

    // ── LEVEL 4 ────────────────────────────────────────────
    {
      name: "Hurried Repairs",
      level: "4",
      initiative: 25,
      imageUrl: BASE_BM + "cs-hurried-repairs.png",
      tags: ["heal", "utility"],
      builds: ["both"],
      top: { text: "Self-heal or repair effect", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "The Bombard's self-sustain option. Fast initiative 25 lets you patch up before the next wave of attacks. The Tank build particularly appreciates self-healing to offset the damage being soaked while holding position.",
    },
    {
      name: "Powerful Buckshot",
      level: "4",
      initiative: 84,
      imageUrl: BASE_BM + "cs-powerful-buckshot.png",
      tags: ["attack"],
      builds: ["projectile"],
      top: { text: "Strong ranged attack", isLoss: false },
      bottom: { text: "Large ranged attack Loss", isLoss: true },
      commentary: "Very slow initiative 84 sits perfectly at the back of the round for Projectile timing. The bottom Loss delivers one of the stronger ranged hits available at Level 4 — worth holding in reserve for critical moments on a 9-card class.",
    },

    // ── LEVEL 5 ────────────────────────────────────────────
    {
      name: "Sharpened Focus",
      level: "5",
      initiative: 32,
      imageUrl: BASE_BM + "cs-sharpened-focus.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Enhanced Projectile or Pierce attack", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "Pierce is one of the Bombard's core strengths — this class is specifically called out as well-equipped to deal with high-Shield problem enemies through Pierce. Sharpened Focus leans into that toolkit at Level 5.",
    },
    {
      name: "Unbreakable Position",
      level: "5",
      initiative: 15,
      imageUrl: BASE_BM + "cs-unbreakable-position.png",
      tags: ["shield", "persistent"],
      builds: ["tank"],
      top: { text: "Strong persistent Shield or defensive stance", isLoss: false },
      bottom: { text: "Shield Loss — major defensive commitment", isLoss: true },
      commentary: "Fast initiative 15 gets your defenses up immediately. The name says it all for the Tank build — hold your position, absorb damage, and keep firing. The bottom Loss is a major defensive commitment that shines in scenarios with prolonged combat against melee-heavy enemy compositions.",
    },

    // ── LEVEL 6 ────────────────────────────────────────────
    {
      name: "Meteoric Blast",
      level: "6",
      initiative: 26,
      imageUrl: BASE_BM + "cs-meteoric-blast.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Powerful ranged attack, Projectile or direct", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "A strong mid-game damage card at fast initiative 26. The Bombard's Projectile build starts hitting its stride at Level 6 with consistent Pierce and Immobilize options complementing raw damage like this.",
    },
    {
      name: "Prolific Perforation",
      level: "6",
      initiative: 62,
      imageUrl: BASE_BM + "cs-prolific-perforation.png",
      tags: ["attack", "aoe"],
      builds: ["projectile"],
      top: { text: "AoE Pierce attack Loss", isLoss: false },
      bottom: { text: "AoE attack Loss", isLoss: true },
      commentary: "Both halves are AoE, making this a high-value card for dense rooms. The Pierce on the top AoE is particularly strong against armored enemies — Prolific Perforation earns its name by punching through defenses across multiple targets simultaneously.",
    },

    // ── LEVEL 7 ────────────────────────────────────────────
    {
      name: "Airborne Skyrocket",
      level: "7",
      initiative: 55,
      imageUrl: BASE_BM + "cs-airborne-skyrocket.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "High-arc Projectile attack, long range", isLoss: false },
      bottom: { text: "Move with jump or elevation utility", isLoss: false },
      commentary: "A thematic and mechanically strong card at medium initiative 55. Long-range Projectile attacks let the Bombard engage targets that other classes can't safely reach, reinforcing the exclusive ranged identity of the class.",
    },
    {
      name: "Ballistic Barrage",
      level: "7",
      initiative: 73,
      imageUrl: BASE_BM + "cs-ballistic-barrage.png",
      tags: ["attack", "projectile"],
      builds: ["projectile"],
      top: { text: "Multi-hit Projectile barrage Loss", isLoss: true },
      bottom: { text: "Move", isLoss: false },
      commentary: "A big Loss payoff at slow initiative 73 — ideal for Projectile timing. Multiple hits on a single target or spread across several makes this a top candidate for boss fights or elite clusters where the Loss cost is justified by the damage output.",
    },

    // ── LEVEL 8 ────────────────────────────────────────────
    {
      name: "Defense Mechanism",
      level: "8",
      initiative: 18,
      imageUrl: BASE_BM + "cs-defense-mechanism.png",
      tags: ["shield", "utility"],
      builds: ["tank"],
      top: { text: "Powerful defensive mechanism, Shield or immunity", isLoss: false },
      bottom: { text: "Move or reactive utility", isLoss: false },
      commentary: "Fast initiative 18 gets the Bombard's defenses online early. At Level 8, the Tank build's shielding options become formidable — Defense Mechanism represents the class's mature defensive toolkit, letting you absorb punishment while Projectiles do their work.",
    },
    {
      name: "Quadruple Cannons",
      level: "8",
      initiative: 86,
      imageUrl: BASE_BM + "cs-quadruple-cannons.png",
      tags: ["attack", "aoe"],
      builds: ["projectile"],
      top: { text: "Four-cannon AoE attack", isLoss: false },
      bottom: { text: "Move", isLoss: false },
      commentary: "The natural evolution of Double Cannons — four barrels of AoE punishment at very slow initiative 86. By Level 8 this is a tremendous Projectile payoff card, hitting multiple enemies simultaneously with the full power of a late-game Bombard.",
    },

    // ── LEVEL 9 ────────────────────────────────────────────
    {
      name: "Supercharged Gunpowder",
      level: "9",
      initiative: 90,
      imageUrl: BASE_BM + "cs-supercharged-gunpowder.png",
      tags: ["attack", "aoe", "projectile"],
      builds: ["projectile"],
      top: { text: "Massive AoE attack, supercharged damage", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "The slowest non-Loss card in the deck at initiative 90 — perfectly positioned for Projectile setup that fires the following round. A fully-built Bombard at Level 9 unleashing Supercharged Gunpowder is the culmination of the class's damage identity.",
    },
    {
      name: "Superior Upgrade",
      level: "9",
      initiative: 9,
      imageUrl: BASE_BM + "cs-superior-upgrade.png",
      tags: ["utility", "persistent"],
      builds: ["tank"],
      top: { text: "Major persistent upgrade or enhancement Loss", isLoss: true },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "The fastest initiative in the Level 9 options at just 9 — nearly as fast as Stationary Enhancements. The Loss top represents the Bombard's ultimate defensive or utility upgrade, a fitting capstone for a Tank build that has spent the campaign building toward an unbreakable position.",
    },

    // ── LEVEL M (MILESTONE REWARD) ──────────────────────────
    {
      name: "Pummeling Chain",
      level: "M",
      initiative: 17,
      imageUrl: BASE_WH_BM + "milestone-ability-cards/trail-of-ashes/toa-msa-bombard.png",
      tags: ["attack", "projectile"],
      builds: ["both"],
      top: { text: "Chained Projectile or multi-hit attack", isLoss: false },
      bottom: { text: "Move or utility", isLoss: false },
      commentary: "Permanently added to your hand once the milestone is complete. Fast initiative 17 slots neatly into the Bombard's late/early initiative strategy. Adds another Projectile trigger opportunity, both for damage and toward future campaign milestones.",
    },
  ],

  perks: [
    { count: 1, text: "Remove two -1 cards" },
    { count: 1, text: "Replace two +0 cards with two +0 PIERCE 3 ↺ cards" },
    { count: 2, text: "Replace one -1 card with one +0 '(+3) if Projectile' card" },
    { count: 2, text: "Add one +2 IMMOBILIZE card" },
    { count: 1, text: "Replace one +1 card with two +1 'Retaliate 1, Range 3' cards" },
    { count: 1, text: "Add two +1 'PULL 3, Self, toward the target' cards" },
    { count: 1, text: "Add one +0 'STRENGTHEN, Self' card" },
    { count: 1, text: "Add one +0 STUN card" },
    { count: 1, text: "Add one +1 WOUND card" },
    { count: 1, text: "Add two +0 'Shield 1, Self' ↺ cards" },
    { count: 1, text: "Add two +0 'Heal 1, Self' ↺ cards" },
    { count: 1, text: "Ignore negative scenario effects and remove one +0 card" },
    { count: 1, text: "Ignore negative item effects and remove one +0 card" },
  ],

  tips: [
    {
      category: "🎯 Class Identity",
      text: "Limited movement is the class's core constraint — Bombards are not nimble. The primary movement mechanic involves latching onto enemies with the Grappling Hook and pulling yourself toward them rather than moving normally. This flips the usual ranged playstyle: instead of kiting away from enemies, you're actively pulling yourself toward targets to set up Projectile hexes. Plan movement carefully and in advance every round.",
    },
    {
      category: "💣 The Projectile Mechanic",
      text: "Place a Projectile token on a specific hex during your turn. At the beginning of your NEXT turn, if an enemy is standing on that hex, the Projectile detonates and deals damage. This is the key timing rule: damage triggers at the START of your turn, before normal actions. This means if an enemy's initiative is higher than yours next round, they will move off the hex before the Projectile fires — and you lose the hit.",
    },
    {
      category: "💣 The Projectile Mechanic",
      text: "Because Projectile damage fires before your normal turn action, you essentially get two turns' worth of attacks in one round — the detonating Projectile from last round PLUS a standard attack this round. This is the source of the class's devastating 'double-turn' potential. Coordinate with allies who can Stun or Immobilize to keep targets pinned on your Projectile hexes and prevent them from walking away before detonation.",
    },
    {
      category: "💣 The Projectile Mechanic",
      text: "Important line-of-sight rule: the Bombard does NOT need to maintain line-of-sight to the Projectile's target through the following round. Line-of-sight is only checked when the ability card is played and the Projectile token is placed. When your next turn starts, the attack on the Projectile hex occurs automatically based on the conditions set at placement — where the Bombard is located or whether it currently has line-of-sight on the following turn does not matter. This gives tremendous tactical flexibility in positioning between turns.",
    },
    {
      category: "📊 Initiative Strategy",
      text: "The Bombard largely relies on slower and middle initiatives. The key pattern is combining slow-initiative 'setup' rounds (place Projectile late, after enemies have moved and revealed positions) with faster-initiative rounds (detonate early next round before enemies act again). Cards like Rolling into Position (14) give you the fast half of this pair, while Consistent Firing (76), Exploding Cannonball (88), and Supercharged Gunpowder (90) give you the slow Projectile-setup half.",
    },
    {
      category: "🚪 Door-Opening Advantage",
      text: "The Bombard's unique initiative timings and shielding make it highly capable on door-opening rounds. Open a door late in the round after enemies have advanced into the room, place a Projectile on a hex where an enemy is standing, then act early next round to detonate before they can escape. Combined with strong Shield options for absorbing the first wave of incoming attacks, this is the class's signature play pattern.",
    },
    {
      category: "🛡️ Shielding & Durability",
      text: "The Bombard's Shield cards are tailored specifically for either melee OR ranged attacks — not both simultaneously. Read the enemy composition carefully before the room opens and select the appropriate Shield type. Ranged Retaliate (Distant Retribution) is a situational all-star that punishes enemies for shooting at you. The high health pool lets you absorb hits while executing your Projectile strategy.",
    },
    {
      category: "🎯 Status Effects",
      text: "Immobilize is your best friend for keeping enemies on Projectile hexes. Pierce cuts through high-Shield problem enemies that would otherwise shrug off your ranged attacks. Stun at Level 1 (Unexpected Bombshell) is rare and valuable — use it on elites or bosses that would otherwise escape your Projectiles. These control tools make the Bombard well-equipped to handle problem enemies that other ranged classes struggle with.",
    },
    {
      category: "🤝 Ally Coordination",
      text: "Awareness of monster AI is critical — you need to predict where enemies will be standing next round when your Projectiles detonate. Coordinate with allies to funnel enemies into your Projectile hexes: a tank can body-block escape routes, a Stun from any ally buys an extra round on the hex, and Immobilize from your own cards keeps targets locked in place. Projectiles that miss because an enemy moved away are wasted stamina on a 9-card class.",
    },
    {
      category: "📈 Perks",
      text: "The '(+3) if Projectile' double-perk is the class's signature modifier — each Projectile trigger becomes a potential +3 damage spike on top of the attack value. Prioritize both copies. Pierce 3 redraw cards complement the class's strength against high-Shield enemies. Immobilize adds a modifier that also locks down enemy movement. Shield 1 Self and Heal 1 Self redraw cards provide passive sustain for the durability build without burning card slots.",
    },
  ],
};